### ISSUE TITLE
Cannot pip install 

### ISSUE THREAD

**Issue by nwunder** [LLNL/SC-PD-FED#2]
Setup is looking for README.rst.

```
# pip install git+https://github.com/LLNL/SC-PD-FED
Collecting git+https://github.com/LLNL/SC-PD-FED
  Cloning https://github.com/LLNL/SC-PD-FED to /tmp/pip-req-build-G8DSuS
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-G8DSuS/setup.py", line 9, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
      File "/usr/lib/ckan/default/lib/python2.7/codecs.py", line 878, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-G8DSuS/README.rst'
```

**Comment by IanLee1521** [comment]
Looks like there was a typo in the `setup.py` file, I just fixed it in: https://github.com/LLNL/SC-PD-FED/commit/2d0f12d2897d566ae17be3e08ba03b886d4b0966 and it appears to install for me now.
